package buginducingcommitanalyzer.repowrapper;

public enum Overlap {
	REF_INSIDE_CHANGE,
	CHANGE_INSIDE_REF,
	//
	REF_BEFORE_OUTSIDE_CHANGE,
	CHANGE_BEFORE_OUTSIDE_REF,
	//
	REF_AFTER_OUTSIDE_CHANGE,
	CHANGE_AFTER_OUTSIDE_REF,
	//
	REF_AND_CHANGE_HAVE_PARTIAL_OVERLAP,
	// 
	NO_OVERLAPS,
	
	ENTITY_INSIDE_CHANGE,
	CHANGE_INSIDE_ENTITY,
	
	ENTITY_BEFORE_OUTSIDE_CHANGE,
	ENTITY_AFTER_OUTSIDE_CHANGE,
	
	
	ENTITY_AND_CHANGE_HAVE_PARTIAL_OVERLAP,
	
}
